kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aac-data
  labels:
    app: aap2-ctrl  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
